// <auto-generated />
using System;
using DbModel.demoDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbModel.Migrations
{
    [DbContext(typeof(_demoContext))]
    [Migration("20260318005632_migracion_01")]
    partial class migracion_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DbModel.demoDb.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido_paterno");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("date_update");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("DateUpdate"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("direccion");

                    b.Property<int>("IdPersonaTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_persona_tipo");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_documento");

                    b.Property<int>("IdTipoSangre")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_sangre");

                    b.Property<int>("IdTipoSexo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_sexo");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<int>("UserCreate")
                        .HasColumnType("int")
                        .HasColumnName("user_create");

                    b.Property<int?>("UserUpdate")
                        .HasColumnType("int")
                        .HasColumnName("user_update");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPersonaTipo" }, "idx_persona_tipo");

                    b.HasIndex(new[] { "IdTipoDocumento" }, "idx_persona_tipo_documento");

                    b.HasIndex(new[] { "IdTipoSangre" }, "idx_persona_tipo_sangre");

                    b.HasIndex(new[] { "IdTipoSexo" }, "idx_persona_tipo_sexo");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("persona_tipo");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("persona_tipo_documento");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoSangre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("persona_tipo_sangre");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoSexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("persona_tipo_sexo");
                });

            modelBuilder.Entity("DbModel.demoDb.Persona", b =>
                {
                    b.HasOne("DbModel.demoDb.PersonaTipo", "IdPersonaTipoNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdPersonaTipo")
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipo");

                    b.HasOne("DbModel.demoDb.PersonaTipoDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdTipoDocumento")
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipo_documento");

                    b.HasOne("DbModel.demoDb.PersonaTipoSangre", "IdTipoSangreNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdTipoSangre")
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipo_sangre");

                    b.HasOne("DbModel.demoDb.PersonaTipoSexo", "IdTipoSexoNavigation")
                        .WithMany("Persona")
                        .HasForeignKey("IdTipoSexo")
                        .IsRequired()
                        .HasConstraintName("fk_persona_tipo_sexo");

                    b.Navigation("IdPersonaTipoNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");

                    b.Navigation("IdTipoSangreNavigation");

                    b.Navigation("IdTipoSexoNavigation");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipo", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoDocumento", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoSangre", b =>
                {
                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DbModel.demoDb.PersonaTipoSexo", b =>
                {
                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
